### ISSUE TITLE
Instructions on how to subscribe?

### ISSUE THREAD

**Issue by mithro** [sifive/last-week-in-risc-v#1]
The "Last Week in RISC-V", a weekly newsletter tracking the RISC-V community sounds really cool. However, I can't seem to find a way to "subscribe" to get the newsletter in my email?

**Comment by justinclift** [comment]
These seem to be the source items for the "Last Week in RISC-V" blog on the SiFive website.

The bottom of those - when published - contain a subscribe form that should do the job.  eg:

&nbsp; &nbsp; https://www.sifive.com/blog/2018/09/07/last-week-in-risc-v/

That being said, having the subscribe instructions in the repo README would probably be useful too. :smile:

**Comment by palmer-dabbelt** [comment]
We're trying to figure out how to make a newsletter specific to "Last Week in RISC-V".  For now you should be able to subscribe to the blog.
