### ISSUE TITLE
2018-09-14 issue didn't make it to the blog?

### ISSUE THREAD

**Issue by justinclift** [sifive/last-week-in-risc-v#3]
Looking at the [SiFive Blog](https://www.sifive.com/blog/) atm, the latest entry is the [7th September one](https://www.sifive.com/blog/2018/09/07/last-week-in-risc-v/).

Did the 14th September entry get missed? :wink:

**Comment by palmer-dabbelt** [comment]
Looks like it.  @nickjalbert do you mind putting the September 7th entry on the blog?

Thanks!

**Comment by nickjalbert** [comment]
@palmer-dabbelt @justinclift will be up shortly

**Comment by nickjalbert** [comment]
[Sept 14th entry is now up](https://www.sifive.com/blog/2018/09/14/last-week-in-risc-v/).  

[The SiFive blog](https://www.sifive.com/blog/) is now synced with this repo as far as LWIRV goes; let me know if you need anything else!

**Comment by nickjalbert** [comment]
Also, thanks for the heads up! :)

**Comment by justinclift** [comment]
No worries at all. :smile:
