### ISSUE TITLE
Entire SiFive blog appears to be offline?

### ISSUE THREAD

**Issue by justinclift** [sifive/last-week-in-risc-v#4]
Just tried going to the SiFive blog, and the whole thing is 404.

* https://www.sifive.com/blog/
* https://www.sifive.com/blog/2018/09/07/last-week-in-risc-v/  <-- previously known to work

Misconfiguration? :wink:

**Comment by jim-wilson** [comment]
We have a new web site design.  The blog is temporarily offline due to the web site rewrite, but it will be re-added soon.

**Comment by justinclift** [comment]
No worries, thanks @jim-wilson. :smile:

**Comment by palmer-dabbelt** [comment]
It's still temporarily offline.

**Comment by richardxia** [comment]
We're still in the process of converting the blog over to the new site and hope to have it back next week. Sorry for the inconvenience!

**Comment by richardxia** [comment]
I'm happy to announce that the blog is back online! All the old links should still work, but please let us know if you encounter any dead links.

https://www.sifive.com/blog

**Comment by justinclift** [comment]
@richardxia It's not quite there yet.

* Right hand side, all items have "Invalid date" for their text:

![sifive-201810201618-blog_errors_1](https://user-images.githubusercontent.com/406299/47251759-12bdcb80-d484-11e8-8bcf-d5caaabff5a0.png)

* When going to that bare [`/blog`](https://www.sifive.com/blog) url, the latest entry shown is 28th September.  The two (so far) entries for October in the repo look like they're missing.

**Comment by richardxia** [comment]
> Right hand side, all items have "Invalid date" for their text:

@justinclift, does the right sidebar show "Invalid Date" even after you refresh? It looks fine for me on my OS and Browser (macOS + Chrome).

> When going to that bare /blog url, the latest entry shown is 28th September. The two (so far) entries for October in the repo look like they're missing.

@palmer-dabbelt will need to send these newer posts to our internal team to post on our site, now that the blog is back online :)

**Comment by justinclift** [comment]
> does the right sidebar show "Invalid Date" even after you refresh? It looks fine for me on my OS and Browser (macOS + Chrome).

After clearing the cache and all cookies in my browser (CentOS 7 x86_64 + Firefox from CentOS repos)... no change.  They're all showing as "Invalid Date".

> ... will need to send these newer posts to our internal team to post on our site, now that the blog is back online

Would the better approach be to verify the blog is in a "known good" state (eg verified in several browsers, with all content up-to-date) before widely announcing it as ready to end users?

**Comment by richardxia** [comment]
Yes, sorry about that. It looks like it was broken on Firefox across all OSs. We've pushed out a fix.

> Would the better approach be to verify the blog is in a "known good" state (eg verified in several browsers, with all content up-to-date) before widely announcing it as ready to end users?

Yep, we should have tested it across more browsers before pushing it out. We'll try to get the newer posts up as soon as possible, but we thought that the demand for the previous content was high enough that it was worth pushing out what we had before getting the new posts in. Thanks for your patience, and I'll post an update once the newer posts are online.

**Comment by richardxia** [comment]
The recent Last Week in RISC-V blog posts are now online:

https://www.sifive.com/blog/last-week-in-risc-v-october-12-2018
https://www.sifive.com/blog/last-week-in-risc-v-october-19-2018

Thank you for your patience.
