### ISSUE TITLE
A blog post is blocked by a URL redirect loop

### ISSUE THREAD

**Issue by crab2313** [sifive/last-week-in-risc-v#8]
https://www.sifive.com/blog/2017/08/21/all-aboard-part-2-relocations/
https://www.sifive.com/blog/all-aboard-part-2-relocations/

**Comment by richardxia** [comment]
Thanks for reporting this issue. We'll try to fix this as soon as possible.

**Comment by richardxia** [comment]
The redirect has been fixed, so both those links work now. Thanks again for reporting the issue!
